# Generated by Django 5.1.7 on 2025-03-19 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ARTIST_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
