# Generated by Django 5.1.7 on 2025-03-29 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ARTIST_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists_managed', to='profiles.userprofile'),
        ),
    ]
