# Generated by Django 5.1.7 on 2025-03-29 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_alter_artist_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__role': 'ARTIST_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
