# Generated by Django 5.1.7 on 2025-03-29 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_alter_artist_manager'),
        ('profiles', '0002_alter_userprofile_address_alter_userprofile_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__role': 'ARTIST_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists_managed', to='profiles.userprofile'),
        ),
    ]
