# Generated by Django 5.1.7 on 2025-03-19 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('COUNTRY', 'Country'), ('CLASSICAL', 'Classical'), ('JAZZ', 'Jazz')], max_length=20)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='albums.album')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
