# Generated by Django 5.1.7 on 2025-03-19 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='album/')),
                ('no_of_tracks', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
